### PR TITLE
Update for latest party packs

### PR DESCRIPTION
**Pull request by StratusFearMe21**
Two years ago, I opened #3 to support the latest Jackbox games, and implement the `lock` opcode. And two years of improving my skills later, I've finally figured it out. This now works with Jackbox Party Pack 9. I've tested Roomerang and Quixort so far, I'll update on more games that I test that work

### CODE REVIEW

**Comment by InvoxiPlayGames** [comment]
Thanks a bunch for the PR! I'll test it with Party Pack 7 and get a friend to test with 8 and 9, and then if it all works I can merge.

**Comment by StratusFearMe21** [comment]
Tested working so far

- Fibbage 4
- Junktopia
- Roomerang
- Nonsensory
- Quixort

Working on

- ~~Nonsensory ("doodle/*" opcodes)~~

**Comment by StratusFearMe21** [comment]
Unfortunately, it appears that FixyText from Jackbox Party Pack 10 is a no-go for this server. Unless you know what a `text-map` is
```
2024-05-20T23:38:41.118301Z DEBUG johnbox: to ecast role=Host {
  "opcode": "text-map/create",
  "params": {
    "acl": [
      "rw id:2",
      "rw id:3",
      "rw id:4"
    ],
    "key": "writing:1",
    "reject": {
      "lexicon": [
        "hate"
      ]
    },
    "val": "uh...i think i’m...good."
  },
  "seq": 119
}

2024-05-20T23:38:41.133605Z DEBUG johnbox: ecast to role=Host {
  "pc": 150,
  "re": 119,
  "opcode": "ok",
  "result": {}
}

2024-05-20T23:38:41.137889Z DEBUG johnbox: ecast to role=Player {
  "pc": 150,
  "opcode": "text-map",
  "result": {
    "key": "writing:1",
    "from": 1,
    "root": "AQIBAAcBB2RlZmF1bHQCBAEFZWNhc3QadWguLi5pIHRoaW5rIGnigJltLi4uZ29vZC4A"
  }
}

2024-05-20T23:38:41.137913Z DEBUG johnbox: ecast to role=Player {
  "pc": 150,
  "opcode": "text-map",
  "result": {
    "key": "writing:1",
    "from": 1,
    "root": "AQIBAAcBB2RlZmF1bHQCBAEFZWNhc3QadWguLi5pIHRoaW5rIGnigJltLi4uZ29vZC4A"
  }
}
```
Unfortunately, it seems like the server does all of the heavy lifting for this data type, and it's communication is in a byte format encoded in base64

IDK, maybe I'll take a wack at it eventually. If I had to guess, I'd say we're looking at some sort of [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type), but I'm not sure on that.

**Comment by StratusFearMe21** [comment]
Finished testing and implementing opcodes for TJPP10

Tested and working:

- Tee K.O. 2
- Timejinx
- Dodo Re Mi
- Hypnotorious

Unimplemented:

- FixyText (Requires complex `text-map/*` opcodes)

**Comment by StratusFearMe21** [comment]
Tested with entirety of TJPP8

Working and tested:

- Drawful: Animate
- The Wheel of Enormous Proportions
- Job Job
- The Poll Mine
- Weapons Drawn

If only all this could be unit tested

**Comment by StratusFearMe21** [comment]
FixyText `text-map` might be a [G-Set CRDT](https://en.m.wikipedia.org/wiki/Conflict-free_replicated_data_type#G-Set_(Grow-only_Set))

**Comment by InvoxiPlayGames** [comment]
Thanks so much for all the contributions - let me know if you want them merged now or if you'd rather wait until `text-map` is implemented.

If you have Discord, reach out to me (username is `invoxiplaygames`), would love to discuss giving you direct push access

**Comment by StratusFearMe21** [comment]
A. You can merge now, I definitely won't be able to find the time to implement `text-map`
B. Sent you a friend request on Discord

**Comment by InvoxiPlayGames** [comment]
Thanks! I, might've accidentally denied your friend request, sorry, could you send one again?

**Comment by StratusFearMe21** [comment]
Alright, sent another one!

**Comment by StratusFearMe21** [comment]
Looking at the JS for fixytext, they appear to be using https://github.com/yjs/yjs

**Pull request merged**
